### ISSUE TITLE
：D

### ISSUE THREAD

**Issue by zjhJOJO** [steffensbola/furg-fire-dataset#2]
i am a greenhand， i  have a question
<annotations>
      <_>
        453 183 232 436</_></annotations></_>
what does the four numbers mean?

**Comment by steffensbola** [comment]
They are OpenCv rectangle definitions. This XML was generated using an old version of OpenCv and hasn't (probably won't) been updated since. 

Rect(int x, int y, int width, int height)   _x_ and _y_ are the top left corner.
For more info, have a look at the documentation: [OpenCv Rect](https://docs.opencv.org/java/2.4.9/org/opencv/core/Rect.html)
