### ISSUE TITLE
how use opencv to read xml file

### ISSUE THREAD

**Issue by Egolee0713** [steffensbola/furg-fire-dataset#3]
hi, I  want to know how use opencv to read xml file, and then to get box coordinate in different frame

**Comment by steffensbola** [comment]
It is a standard xml file. You should be able to navigate it using basic OpenCv functions. See the documentation for the version that was used to create the files: https://docs.opencv.org/2.4/doc/tutorials/core/file_input_output_with_xml_yml/file_input_output_with_xml_yml.html

The code used to be available in the http://www.cvworks.c3.furg.br framework but it seem the SVN repo is now password proected. I no longer have access since I no longer work at the university.

Have a look on that OpenCv documentation. Let me know if you are unable to make it work. I might have a copy of the code somewhere but that is going to take some time to find.

**Comment by Egolee0713** [comment]
hi, I have make progress, but I find something strange.  For example, in barbecue.xml, a rect (453 183 232 436) is for frame 0 of barbecue.mp4, but in Annotations, there is a file named barbecue0.xml, there is a rect(191, 109,  288,  371) is also for for frame 0 of barbecue.mp4? I don't know if  I make some wrong, why they are different, (resize or ?). And  after I draw both of them in the frame, I find neither of them is  right why？

**Comment by steffensbola** [comment]
There is no such file as `barbecue0.xml` in the master branch. Perhaps you accidently renamed it?
There is only ONE `xml` file for each video.
ONE video has ZERO or MANY frames. 
ONE frame may have ZERO or MANY annotation rectangles.

**Comment by Egolee0713** [comment]
OK, now I have already successfully parse the xml fle by opencv-python, and finally get the right annnotation result.  Thanks for your help , and may be later I will upload a copy.

**Comment by fusang1337** [comment]
> OK, now I have already successfully parse the xml fle by opencv-python, and finally get the right annnotation result. Thanks for your help , and may be later I will upload a copy.

您好，我正在做火焰检测的研究，请问您那边有相关的数据集么？不胜感激，原意为您的标注和辛苦劳动付费

**Comment by steffensbola** [comment]
This would be a very welcome contribution @fusang1337 
If you got the code or even the annotations in another format (json, pixel-wise segmentation, or any other format) please open a PR.
I am certain it will help many other researchers.
